{% set name = "dash" %}
{% set version = "1.21.0" %}
{% set sha256 = "8b03a53e4f7a5f3eded8af099ff54d9981f7879d22d74c7970b9a27c8f698ebb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python ==2.7.*|>=3.3
    - setuptools
    - pip
  run:
    - python ==2.7.*|>=3.3
    - pyyaml >=5.1.1
    - flask >=1.0.4
    - flask-compress
    - plotly
    - dash-renderer ==1.9.1
    - dash-core-components ==1.17.1
    - dash-html-components ==1.1.4
    - dash-table ==4.12.0
    - future
    
test:
  imports:
    - dash.dash
    - dash.dependencies
    - dash.exceptions
    - dash.resources

about:
  home: https://plot.ly/dash
  dev_url: https://github.com/plotly/dash
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python framework for building reactive web-apps.

extra:
  recipe-maintainers:
    - bandersen23
    - moorepants